In [1]:
import pandas as pd

In [2]:

def load_data(file_path):
    try: 
        data = pd.read_csv(file_path)
        print("Data loaded successfully.")
        return data
    except Exception as e:
        print(f"Error loading data: {e}")
        return None
    
data = load_data("/Users/andresrodartee/Desktop/eada/Deep Learning/book-rec/books_DL.csv")

data.head()

Data loaded successfully.

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0

In [3]:
import numpy as np

In [4]:
print(data.columns)
data.info()

Index(['isbn13', 'isbn10', 'title', 'subtitle', 'authors', 'categories',
       'thumbnail', 'description', 'published_year', 'average_rating',
       'num_pages', 'ratings_count'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   int64
 1   isbn10          6810 non-null   str
 2   title           6810 non-null   str
 3   subtitle        2381 non-null   str
 4   authors         6738 non-null   str
 5   categories      6711 non-null   str
 6   thumbnail       6481 non-null   str
 7   description     6548 non-null   str
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), int64(1), str(7)
memory usage: 638.6 KB

In [17]:
df = data[['title', 'authors', 'description', 'average_rating', 'categories', 'published_year', 'ratings_count' ]]
df.head()

,title,authors,description,average_rating,categories,published_year,ratings_count
0,Gilead,Marilynne Robinson,A NOVEL THAT READERS and critics have been eag...,3.85,Fiction,2004.0,361.0
1,Spider's Web,Charles Osborne;Agatha Christie,A new 'Christie for Christmas' -- a full-lengt...,3.83,Detective and mystery stories,2000.0,5164.0
2,The One Tree,Stephen R. Donaldson,Volume Two of Stephen Donaldson's acclaimed se...,3.97,American fiction,1982.0,172.0
3,Rage of angels,Sidney Sheldon,"A memorable, mesmerizing heroine Jennifer -- b...",3.93,Fiction,1993.0,29532.0
4,The Four Loves,Clive Staples Lewis,Lewis' work on the nature of love divides love...,4.15,Christian life,2002.0,33684.0

In [18]:
print(df.shape)

(6810, 7)

In [19]:
df = df.dropna(subset=['title'])
df['average_rating'] = df['average_rating'].fillna(0)
df['ratings_count'] = df['ratings_count'].fillna(0)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           6810 non-null   str
 1   authors         6738 non-null   str
 2   description     6548 non-null   str
 3   average_rating  6810 non-null   float64
 4   categories      6711 non-null   str
 5   published_year  6804 non-null   float64
 6   ratings_count   6810 non-null   float64
dtypes: float64(3), str(4)
memory usage: 372.6 KB

In [21]:
missing_yrs = df[df['published_year'].isnull()]
print(missing_yrs[['title' , 'authors']])

                                        title                    authors
1114                                Book Club                Yann Martel
1428                            The Civil War               Shelby Foote
1779               The Fellowship of the Ring  John Ronald Reuel Tolkien
3062  Grade 4 Common Core Exemplar Collection                        NaN
3554     Frankenstein: City of Night: A Novel                        NaN
4548              20000 LEAGUES UNDER THE SEA                JULIO VERNE

In [22]:
df.loc[df['title'] == 'Book Club', 'published_year'] = 2012
df.loc[df['title'] == 'The Civil War', 'published_year'] = 1958
df.loc[df['title'] == 'The Fellowship of the Ring', 'published_year'] = 1954
df.loc[df['title'] == 'Grade 4 Common Core Exemplar Collection', 'published_year'] = 2012
df.loc[df['title'] == 'Frankenstein: City of Night: A Novel', 'published_year'] = 2005
df.loc[df['title'] == '20000 LEAGUES UNDER THE SEA', 'published_year'] = 1870

df.loc[df['title'] == 'Frankenstein: City of Night: A Novel', 'authors'] = 'Dean Koontz'

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           6810 non-null   str
 1   authors         6739 non-null   str
 2   description     6548 non-null   str
 3   average_rating  6810 non-null   float64
 4   categories      6711 non-null   str
 5   published_year  6810 non-null   float64
 6   ratings_count   6810 non-null   float64
dtypes: float64(3), str(4)
memory usage: 372.6 KB

In [23]:
df['authors'] = df['authors'].fillna("Unknown Author")
df['categories'] = df['categories'].fillna("Uncategorized")
df['description'] = df['description'].fillna("No description available.")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           6810 non-null   str
 1   authors         6810 non-null   str
 2   description     6810 non-null   str
 3   average_rating  6810 non-null   float64
 4   categories      6810 non-null   str
 5   published_year  6810 non-null   float64
 6   ratings_count   6810 non-null   float64
dtypes: float64(3), str(4)
memory usage: 372.6 KB

Create a weighted rating for the books

In [24]:
C = df['average_rating'].mean()
m = df['ratings_count'].quantile(0.90)

def calculate_weighted_rating(row, m=m, C=C):
    v = row['ratings_count']
    R = row['average_rating']
    if (v + m) == 0:
        return 0
    return (v/(v+m) * R) + (m/(m+v) * C)

df['weighted_rating'] = df.apply(calculate_weighted_rating, axis=1)

In [25]:
df['context_string'] = (
    "Title: " + df['title'] + ". " +
    "Author(s): " + df['authors'] + ". " +
    "Category: " + df['categories'] + ". " +
    "Published: " + df['published_year'].astype(int).astype(str) + ". " +
    "Summary: " + df['description']
)

print("Sample Context String:\n")
print(df['context_string'].iloc[0])
print("\nTop 5 Books by Weighted Rating:")
print(df[['title', 'average_rating', 'ratings_count', 'weighted_rating']].sort_values(by='weighted_rating', ascending=False).head(5))

Sample Context String:

Title: Gilead. Author(s): Marilynne Robinson. Category: Fiction. Published: 2004. Summary: A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.

Top 5 Books by Weighted Rating:
                                                  title  average_rating  \
2723    Harry Potter and the Half-Blood Prince (Book 6)            4.56
2710  Harry Potter and the Prisoner of Azkaban (Book 3)            4.55
1780                         The Fellowship of the Ring            4.52
2676  Harry Potter and the Order of the Phoenix (Boo...            4.49
5346                    The Essential Calvin And Hobbes            4.64

      ratings_count  weighted_rating
2723      1944099.0         4.550611
2710      2149872.0         4.541629
1780       532629.0         4.489018
2676      1996446.0         4.481837
5346       102955.0         4.481730