In [1]:
import pandas as pd

In [2]:

def load_data(file_path):
    try: 
        data = pd.read_csv(file_path)
        print("Data loaded successfully.")
        return data
    except Exception as e:
        print(f"Error loading data: {e}")
        return None
    
data = load_data("/Users/andresrodartee/Desktop/eada/Deep Learning/book-rec/data/books_DL.csv")

data.head()

Data loaded successfully.

,title,authors,description,average_rating,categories,published_year,ratings_count,weighted_rating,context_string
0,Gilead,Marilynne Robinson,A NOVEL THAT READERS and critics have been eag...,3.85,Fiction,2004.0,361.0,3.907715,Title: Gilead. Author(s): Marilynne Robinson. ...
1,Spider's Web,Charles Osborne;Agatha Christie,A new 'Christie for Christmas' -- a full-lengt...,3.83,Detective and mystery stories,2000.0,5164.0,3.896387,Title: Spider's Web. Author(s): Charles Osborn...
2,The One Tree,Stephen R. Donaldson,Volume Two of Stephen Donaldson's acclaimed se...,3.97,American fiction,1982.0,172.0,3.908818,Title: The One Tree. Author(s): Stephen R. Don...
3,Rage of angels,Sidney Sheldon,"A memorable, mesmerizing heroine Jennifer -- b...",3.93,Fiction,1993.0,29532.0,3.919430,Title: Rage of angels. Author(s): Sidney Sheld...
4,The Four Loves,Clive Staples Lewis,Lewis' work on the nature of love divides love...,4.15,Christian life,2002.0,33684.0,4.039454,Title: The Four Loves. Author(s): Clive Staple...

In [3]:
import numpy as np

In [4]:
print(data.columns)
data.info()

Index(['title', 'authors', 'description', 'average_rating', 'categories',
       'published_year', 'ratings_count', 'weighted_rating', 'context_string'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            6810 non-null   str
 1   authors          6810 non-null   str
 2   description      6810 non-null   str
 3   average_rating   6810 non-null   float64
 4   categories       6810 non-null   str
 5   published_year   6810 non-null   float64
 6   ratings_count    6810 non-null   float64
 7   weighted_rating  6810 non-null   float64
 8   context_string   6810 non-null   str
dtypes: float64(4), str(5)
memory usage: 479.0 KB

In [5]:
df = data[['title', 'authors', 'description', 'average_rating', 'categories', 'published_year', 'ratings_count' ]]
df.head()

,title,authors,description,average_rating,categories,published_year,ratings_count
0,Gilead,Marilynne Robinson,A NOVEL THAT READERS and critics have been eag...,3.85,Fiction,2004.0,361.0
1,Spider's Web,Charles Osborne;Agatha Christie,A new 'Christie for Christmas' -- a full-lengt...,3.83,Detective and mystery stories,2000.0,5164.0
2,The One Tree,Stephen R. Donaldson,Volume Two of Stephen Donaldson's acclaimed se...,3.97,American fiction,1982.0,172.0
3,Rage of angels,Sidney Sheldon,"A memorable, mesmerizing heroine Jennifer -- b...",3.93,Fiction,1993.0,29532.0
4,The Four Loves,Clive Staples Lewis,Lewis' work on the nature of love divides love...,4.15,Christian life,2002.0,33684.0

In [6]:
print(df.shape)

(6810, 7)

In [7]:
df = df.dropna(subset=['title'])
df['average_rating'] = df['average_rating'].fillna(0)
df['ratings_count'] = df['ratings_count'].fillna(0)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           6810 non-null   str
 1   authors         6810 non-null   str
 2   description     6810 non-null   str
 3   average_rating  6810 non-null   float64
 4   categories      6810 non-null   str
 5   published_year  6810 non-null   float64
 6   ratings_count   6810 non-null   float64
dtypes: float64(3), str(4)
memory usage: 372.6 KB

In [9]:
missing_yrs = df[df['published_year'].isnull()]
print(missing_yrs[['title' , 'authors']])

Empty DataFrame
Columns: [title, authors]
Index: []

In [10]:
df.loc[df['title'] == 'Book Club', 'published_year'] = 2012
df.loc[df['title'] == 'The Civil War', 'published_year'] = 1958
df.loc[df['title'] == 'The Fellowship of the Ring', 'published_year'] = 1954
df.loc[df['title'] == 'Grade 4 Common Core Exemplar Collection', 'published_year'] = 2012
df.loc[df['title'] == 'Frankenstein: City of Night: A Novel', 'published_year'] = 2005
df.loc[df['title'] == '20000 LEAGUES UNDER THE SEA', 'published_year'] = 1870

df.loc[df['title'] == 'Frankenstein: City of Night: A Novel', 'authors'] = 'Dean Koontz'

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           6810 non-null   str
 1   authors         6810 non-null   str
 2   description     6810 non-null   str
 3   average_rating  6810 non-null   float64
 4   categories      6810 non-null   str
 5   published_year  6810 non-null   float64
 6   ratings_count   6810 non-null   float64
dtypes: float64(3), str(4)
memory usage: 372.6 KB

In [11]:
df['authors'] = df['authors'].fillna("Unknown Author")
df['categories'] = df['categories'].fillna("Uncategorized")
df['description'] = df['description'].fillna("No description available.")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           6810 non-null   str
 1   authors         6810 non-null   str
 2   description     6810 non-null   str
 3   average_rating  6810 non-null   float64
 4   categories      6810 non-null   str
 5   published_year  6810 non-null   float64
 6   ratings_count   6810 non-null   float64
dtypes: float64(3), str(4)
memory usage: 372.6 KB

Create a weighted rating for the books

In [12]:
C = df['average_rating'].mean()
m = df['ratings_count'].quantile(0.90)

def calculate_weighted_rating(row, m=m, C=C):
    v = row['ratings_count']
    R = row['average_rating']
    if (v + m) == 0:
        return 0
    return (v/(v+m) * R) + (m/(m+v) * C)

df['weighted_rating'] = df.apply(calculate_weighted_rating, axis=1)

In [13]:
df['context_string'] = (
    "Title: " + df['title'] + ". " +
    "Author(s): " + df['authors'] + ". " +
    "Category: " + df['categories'] + ". " +
    "Published: " + df['published_year'].astype(int).astype(str) + ". " +
    "Summary: " + df['description']
)

print("Sample Context String:\n")
print(df['context_string'].iloc[0])
print("\nTop 5 Books by Weighted Rating:")
print(df[['title', 'average_rating', 'ratings_count', 'weighted_rating']].sort_values(by='weighted_rating', ascending=False).head(5))

Sample Context String:

Title: Gilead. Author(s): Marilynne Robinson. Category: Fiction. Published: 2004. Summary: A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.

Top 5 Books by Weighted Rating:
                                                  title  average_rating  \
2723    Harry Potter and the Half-Blood Prince (Book 6)            4.56
2710  Harry Potter and the Prisoner of Azkaban (Book 3)            4.55
1780                         The Fellowship of the Ring            4.52
2676  Harry Potter and the Order of the Phoenix (Boo...            4.49
5346                    The Essential Calvin And Hobbes            4.64

      ratings_count  weighted_rating
2723      1944099.0         4.550611
2710      2149872.0         4.541629
1780       532629.0         4.489018
2676      1996446.0         4.481837
5346       102955.0         4.481730